name: SurvivalGame
api: 1.0.0
version: 1.0.10
main: Andre\SurvivalGame\Main
load: POSTWORLD
author: AndreTheGamer
website: https://github.com/andrethegamer/survivalgame


commands:
 sg:
  permission: survivalgame.command.sg
  description: SurvivalGame Main Command
  usage: §b/sg §d<set> §dto set a arena or §b<remove> §dto remove current settings
 lobby:
  permission: SurvivalGame.command.lobby
  description: back to lobby
  usage: /lobby
permissions:
 SurvivalGame.*:
  description: the main permission
  default: op
  children:
   SurvivalGame.command.*:
    description: use commands in plugin
    default: op
    children:
     SurvivalGame.command.lobby:
      description: back to lobby
      default: true
     SurvivalGame.command.sg:
      description: set SurvivalGame
      default: op
   sg.touch.startgame:
    description: click the sign and join the game
    default: true
